# VibeCode 环境变量重命名脚本
# 将 CLAUDE_CODE_ 前缀的环境变量替换为 VIBECODE_ 前缀

$ErrorActionPreference = "Stop"

# 定义需要替换的环境变量映射
$envVarMappings = @{
    # 核心认证相关
    'CLAUDE_CODE_OAUTH_TOKEN' = 'VIBECODE_OAUTH_TOKEN'
    'CLAUDE_CODE_OAUTH_REFRESH_TOKEN' = 'VIBECODE_OAUTH_REFRESH_TOKEN'
    'CLAUDE_CODE_OAUTH_SCOPES' = 'VIBECODE_OAUTH_SCOPES'
    'CLAUDE_CODE_OAUTH_CLIENT_ID' = 'VIBECODE_OAUTH_CLIENT_ID'
    'CLAUDE_CODE_CUSTOM_OAUTH_URL' = 'VIBECODE_CUSTOM_OAUTH_URL'
    'CLAUDE_CODE_SESSION_ACCESS_TOKEN' = 'VIBECODE_SESSION_ACCESS_TOKEN'
    'CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR' = 'VIBECODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR'
    'CLAUDE_CODE_ACCOUNT_TAGGED_ID' = 'VIBECODE_ACCOUNT_TAGGED_ID'
    'CLAUDE_CODE_ORGANIZATION_UUID' = 'VIBECODE_ORGANIZATION_UUID'

    # 远程/桥接模式
    'CLAUDE_CODE_REMOTE' = 'VIBECODE_REMOTE'
    'CLAUDE_CODE_ENTRYPOINT' = 'VIBECODE_ENTRYPOINT'
    'CLAUDE_CODE_ENVIRONMENT_KIND' = 'VIBECODE_ENVIRONMENT_KIND'
    'CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION' = 'VIBECODE_ENVIRONMENT_RUNNER_VERSION'
    'CLAUDE_CODE_REMOTE_SESSION_ID' = 'VIBECODE_REMOTE_SESSION_ID'
    'CLAUDE_CODE_REMOTE_MEMORY_DIR' = 'VIBECODE_REMOTE_MEMORY_DIR'
    'CLAUDE_CODE_USE_CCR_V2' = 'VIBECODE_USE_CCR_V2'
    'CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V2' = 'VIBECODE_POST_FOR_SESSION_INGRESS_V2'
    'CLAUDE_CODE_WORKER_EPOCH' = 'VIBECODE_WORKER_EPOCH'
    'CLAUDE_CODE_REMOTE_SEND_KEEPALIVES' = 'VIBECODE_REMOTE_SEND_KEEPALIVES'
    'CLAUDE_CODE_FORCE_SANDBOX' = 'VIBECODE_FORCE_SANDBOX'
    'CLAUDE_CODE_CONTAINER_ID' = 'VIBECODE_CONTAINER_ID'

    # 配置目录相关
    'CLAUDE_CODE_CONFIG_DIR' = 'VIBECODE_CONFIG_DIR'
    'CLAUDE_CODE_PLUGIN_CACHE_DIR' = 'VIBECODE_PLUGIN_CACHE_DIR'
    'CLAUDE_CODE_PLUGIN_SEED_DIR' = 'VIBECODE_PLUGIN_SEED_DIR'
    'CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE' = 'VIBECODE_PLUGIN_USE_ZIP_CACHE'
    'CLAUDE_CODE_MANAGED_SETTINGS_PATH' = 'VIBECODE_MANAGED_SETTINGS_PATH'

    # 功能开关
    'CLAUDE_CODE_SIMPLE' = 'VIBECODE_SIMPLE'
    'CLAUDE_CODE_REPL' = 'VIBECODE_REPL'
    'CLAUDE_CODE_PROACTIVE' = 'VIBECODE_PROACTIVE'
    'CLAUDE_CODE_BRIEF' = 'VIBECODE_BRIEF'
    'CLAUDE_CODE_BRIEF_UPLOAD' = 'VIBECODE_BRIEF_UPLOAD'
    'CLAUDE_CODE_COORDINATOR_MODE' = 'VIBECODE_COORDINATOR_MODE'
    'CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS' = 'VIBECODE_EXPERIMENTAL_AGENT_TEAMS'
    'CLAUDE_CODE_AGENT_TEAMS' = 'VIBECODE_AGENT_TEAMS'
    'CLAUDE_CODE_PLAN_MODE_REQUIRED' = 'VIBECODE_PLAN_MODE_REQUIRED'
    'CLAUDE_CODE_ENABLE_TASKS' = 'VIBECODE_ENABLE_TASKS'
    'CLAUDE_CODE_TASK_LIST_ID' = 'VIBECODE_TASK_LIST_ID'
    'CLAUDE_CODE_TEAM_NAME' = 'VIBECODE_TEAM_NAME'
    'CLAUDE_CODE_AGENT_ID' = 'VIBECODE_AGENT_ID'
    'CLAUDE_CODE_AGENT_NAME' = 'VIBECODE_AGENT_NAME'
    'CLAUDE_CODE_AGENT_COLOR' = 'VIBECODE_AGENT_COLOR'
    'CLAUDE_CODE_PARENT_SESSION_ID' = 'VIBECODE_PARENT_SESSION_ID'
    'CLAUDE_CODE_TEAMMATE_COMMAND' = 'VIBECODE_TEAMMATE_COMMAND'
    'CLAUDE_CODE_UNDERCOVER' = 'VIBECODE_UNDERCOVER'
    'CLAUDE_CODE_DISABLE_AUTO_MEMORY' = 'VIBECODE_DISABLE_AUTO_MEMORY'
    'CLAUDE_CODE_DISABLE_CLAUDE_MDS' = 'VIBECODE_DISABLE_CLAUDE_MDS'
    'CLAUDE_CODE_DISABLE_BACKGROUND_TASKS' = 'VIBECODE_DISABLE_BACKGROUND_TASKS'
    'CLAUDE_CODE_DISABLE_ADVISOR_TOOL' = 'VIBECODE_DISABLE_ADVISOR_TOOL'
    'CLAUDE_CODE_DISABLE_CRON' = 'VIBECODE_DISABLE_CRON'
    'CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS' = 'VIBECODE_DISABLE_EXPERIMENTAL_BETAS'
    'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC' = 'VIBECODE_DISABLE_NONESSENTIAL_TRAFFIC'
    'CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP' = 'VIBECODE_DISABLE_PRECOMPACT_SKIP'
    'CLAUDE_CODE_DISABLE_COMMAND_INJECTION_CHECK' = 'VIBECODE_DISABLE_COMMAND_INJECTION_CHECK'
    'CLAUDE_CODE_DISABLE_TERMINAL_TITLE' = 'VIBECODE_DISABLE_TERMINAL_TITLE'
    'CLAUDE_CODE_DISABLE_POLICY_SKILLS' = 'VIBECODE_DISABLE_POLICY_SKILLS'
    'CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL' = 'VIBECODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL'
    'CLAUDE_CODE_ENABLE_XAA' = 'VIBECODE_ENABLE_XAA'
    'CLAUDE_CODE_ENABLE_TELEMETRY' = 'VIBECODE_ENABLE_TELEMETRY'
    'CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION' = 'VIBECODE_ENABLE_PROMPT_SUGGESTION'
    'CLAUDE_CODE_NEW_INIT' = 'VIBECODE_NEW_INIT'
    'CLAUDE_CODE_SKIP_PROMPT_HISTORY' = 'VIBECODE_SKIP_PROMPT_HISTORY'
    'CLAUDE_CODE_SAVE_HOOK_ADDITIONAL_CONTEXT' = 'VIBECODE_SAVE_HOOK_ADDITIONAL_CONTEXT'
    'CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS' = 'VIBECODE_EMIT_SESSION_STATE_EVENTS'
    'CLAUDE_CODE_STREAMLINED_OUTPUT' = 'VIBECODE_STREAMLINED_OUTPUT'
    'CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER' = 'VIBECODE_EXIT_AFTER_FIRST_RENDER'
    'CLAUDE_CODE_EXIT_AFTER_STOP_DELAY' = 'VIBECODE_EXIT_AFTER_STOP_DELAY'
    'CLAUDE_CODE_RESUME_INTERRUPTED_TURN' = 'VIBECODE_RESUME_INTERRUPTED_TURN'
    'CLAUDE_CODE_SYNC_PLUGIN_INSTALL' = 'VIBECODE_SYNC_PLUGIN_INSTALL'
    'CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS' = 'VIBECODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS'
    'CLAUDE_CODE_USE_COWORK_PLUGINS' = 'VIBECODE_USE_COWORK_PLUGINS'
    'CLAUDE_CODE_CCR_MIRROR' = 'VIBECODE_CCR_MIRROR'
    'CLAUDE_CODE_ATTRIBUTION_HEADER' = 'VIBECODE_ATTRIBUTION_HEADER'
    'CLAUDE_CODE_OVERRIDE_DATE' = 'VIBECODE_OVERRIDE_DATE'
    'CLAUDE_CODE_GLOB_TIMEOUT_SECONDS' = 'VIBECODE_GLOB_TIMEOUT_SECONDS'
    'CLAUDE_CODE_SYNTAX_HIGHLIGHT' = 'VIBECODE_SYNTAX_HIGHLIGHT'
    'CLAUDE_CODE_DEBUG_REPAINTS' = 'VIBECODE_DEBUG_REPAINTS'
    'CLAUDE_CODE_COMMIT_LOG' = 'VIBECODE_COMMIT_LOG'
    'CLAUDE_CODE_PROFILE_STARTUP' = 'VIBECODE_PROFILE_STARTUP'
    'CLAUDE_CODE_PROFILE_QUERY' = 'VIBECODE_PROFILE_QUERY'
    'CLAUDE_CODE_SLOW_OPERATION_THRESHOLD_MS' = 'VIBECODE_SLOW_OPERATION_THRESHOLD_MS'
    'CLAUDE_CODE_DUMP_AUTO_MODE' = 'VIBECODE_DUMP_AUTO_MODE'
    'CLAUDE_CODE_AUTO_MODE_MODEL' = 'VIBECODE_AUTO_MODE_MODEL'
    'CLAUDE_CODE_TWO_STAGE_CLASSIFIER' = 'VIBECODE_TWO_STAGE_CLASSIFIER'
    'CLAUDE_CODE_JSONL_TRANSCRIPT' = 'VIBECODE_JSONL_TRANSCRIPT'
    'CLAUDE_CODE_VERIFY_PLAN' = 'VIBECODE_VERIFY_PLAN'
    'CLAUDE_CODE_MCP_INSTR_DELTA' = 'VIBECODE_MCP_INSTR_DELTA'
    'CLAUDE_CODE_USE_NATIVE_FILE_SEARCH' = 'VIBECODE_USE_NATIVE_FILE_SEARCH'
    'CLAUDE_CODE_STREAM_CLOSE_TIMEOUT' = 'VIBECODE_STREAM_CLOSE_TIMEOUT'
    'CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS' = 'VIBECODE_SESSIONEND_HOOKS_TIMEOUT_MS'
    'CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL' = 'VIBECODE_IDE_SKIP_AUTO_INSTALL'
    'CLAUDE_CODE_IDE_SKIP_VALID_CHECK' = 'VIBECODE_IDE_SKIP_VALID_CHECK'
    'CLAUDE_CODE_IDE_HOST_OVERRIDE' = 'VIBECODE_IDE_HOST_OVERRIDE'
    'CLAUDE_CODE_SSE_PORT' = 'VIBECODE_SSE_PORT'
    'CLAUDE_CODE_SHELL' = 'VIBECODE_SHELL'
    'CLAUDE_CODE_SHELL_PREFIX' = 'VIBECODE_SHELL_PREFIX'
    'CLAUDE_CODE_GIT_BASH_PATH' = 'VIBECODE_GIT_BASH_PATH'
    'CLAUDE_CODE_TMPDIR' = 'VIBECODE_TMPDIR'
    'CLAUDE_CODE_TMUX_TRUECOLOR' = 'VIBECODE_TMUX_TRUECOLOR'
    'CLAUDE_CODE_TMUX_SESSION' = 'VIBECODE_TMUX_SESSION'
    'CLAUDE_CODE_TMUX_PREFIX' = 'VIBECODE_TMUX_PREFIX'
    'CLAUDE_CODE_TMUX_PREFIX_CONFLICTS' = 'VIBECODE_TMUX_PREFIX_CONFLICTS'
    'CLAUDE_CODE_USE_POWERSHELL_TOOL' = 'VIBECODE_USE_POWERSHELL_TOOL'
    'CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS' = 'VIBECODE_PWSH_PARSE_TIMEOUT_MS'
    'CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS' = 'VIBECODE_FILE_READ_MAX_OUTPUT_TOKENS'
    'CLAUDE_CODE_MAX_OUTPUT_TOKENS' = 'VIBECODE_MAX_OUTPUT_TOKENS'
    'CLAUDE_CODE_SUBAGENT_MODEL' = 'VIBECODE_SUBAGENT_MODEL'
    'CLAUDE_CODE_AGENT_LIST_IN_MESSAGES' = 'VIBECODE_AGENT_LIST_IN_MESSAGES'
    'CLAUDE_CODE_PLAN_V2_AGENT_COUNT' = 'VIBECODE_PLAN_V2_AGENT_COUNT'
    'CLAUDE_CODE_PLAN_V2_EXPLORE_AGENT_COUNT' = 'VIBECODE_PLAN_V2_EXPLORE_AGENT_COUNT'
    'CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE' = 'VIBECODE_PLAN_MODE_INTERVIEW_PHASE'
    'CLAUDE_CODE_USE_BEDROCK' = 'VIBECODE_USE_BEDROCK'
    'CLAUDE_CODE_USE_VERTEX' = 'VIBECODE_USE_VERTEX'
    'CLAUDE_CODE_USE_FOUNDRY' = 'VIBECODE_USE_FOUNDRY'
    'CLAUDE_CODE_SKIP_BEDROCK_AUTH' = 'VIBECODE_SKIP_BEDROCK_AUTH'
    'CLAUDE_CODE_SKIP_VERTEX_AUTH' = 'VIBECODE_SKIP_VERTEX_AUTH'
    'CLAUDE_CODE_SKIP_FOUNDRY_AUTH' = 'VIBECODE_SKIP_FOUNDRY_AUTH'
    'CLAUDE_CODE_DISABLE_LEGACY_MODEL_REMAP' = 'VIBECODE_DISABLE_LEGACY_MODEL_REMAP'
    'CLAUDE_CODE_CLIENT_CERT' = 'VIBECODE_CLIENT_CERT'
    'CLAUDE_CODE_CLIENT_KEY' = 'VIBECODE_CLIENT_KEY'
    'CLAUDE_CODE_CLIENT_KEY_PASSPHRASE' = 'VIBECODE_CLIENT_KEY_PASSPHRASE'
    'CLAUDE_CODE_PROXY_RESOLVES_HOSTS' = 'VIBECODE_PROXY_RESOLVES_HOSTS'
    'CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST' = 'VIBECODE_PROVIDER_MANAGED_BY_HOST'
    'CLAUDE_CODE_ENHANCED_TELEMETRY_BETA' = 'VIBECODE_ENHANCED_TELEMETRY_BETA'
    'CLAUDE_CODE_PERFETTO_TRACE' = 'VIBECODE_PERFETTO_TRACE'
    'CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S' = 'VIBECODE_PERFETTO_WRITE_INTERVAL_S'
    'CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS' = 'VIBECODE_OTEL_SHUTDOWN_TIMEOUT_MS'
    'CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS' = 'VIBECODE_OTEL_FLUSH_TIMEOUT_MS'
    'CLAUDE_CODE_WORKSPACE_HOST_PATHS' = 'VIBECODE_WORKSPACE_HOST_PATHS'
    'CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING' = 'VIBECODE_STALL_TIMEOUT_MS_FOR_TESTING'
    'CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS' = 'VIBECODE_PLUGIN_GIT_TIMEOUT_MS'
    'CLAUDE_CODE_SUBPROCESS_ENV_SCRUB' = 'VIBECODE_SUBPROCESS_ENV_SCRUB'
    'CLAUDE_CODE_BUBBLEWRAP' = 'VIBECODE_BUBBLEWRAP'
    'CLAUDE_CODE_MESSAGING_SOCKET' = 'VIBECODE_MESSAGING_SOCKET'
    'CLAUDE_CODE_SESSION_ID' = 'VIBECODE_SESSION_ID'
    'CLAUDE_CODE_COWORK' = 'VIBECODE_COWORK'
}

# 获取所有 TypeScript 和 TSX 文件
$files = Get-ChildItem -Path "." -Recurse -Filter "*.ts" -File | Where-Object { $_.FullName -notmatch "node_modules" -and $_.FullName -notmatch "\.git" }
$tsxFiles = Get-ChildItem -Path "." -Recurse -Filter "*.tsx" -File | Where-Object { $_.FullName -notmatch "node_modules" -and $_.FullName -notmatch "\.git" }
$allFiles = $files + $tsxFiles

$totalFiles = $allFiles.Count
$processedFiles = 0
$modifiedFiles = 0

Write-Host "Found $totalFiles files to process..." -ForegroundColor Cyan

foreach ($file in $allFiles) {
    $processedFiles++
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    $originalContent = $content
    $fileModified = $false

    foreach ($oldVar in $envVarMappings.Keys) {
        $newVar = $envVarMappings[$oldVar]

        # 替换 process.env.XXX
        $pattern1 = "process\.env\.$oldVar"
        $replacement1 = "process.env.$newVar"
        if ($content -match $pattern1) {
            $content = $content -replace $pattern1, $replacement1
            $fileModified = $true
        }

        # 替换字符串中的变量名 (用于错误消息等)
        $pattern2 = '"' + $oldVar + '"'
        $replacement2 = '"' + $newVar + '"'
        if ($content -match [regex]::Escape($pattern2)) {
            $content = $content -replace [regex]::Escape($pattern2), $replacement2
            $fileModified = $true
        }

        # 替换单引号字符串
        $pattern3 = "'" + $oldVar + "'"
        $replacement3 = "'" + $newVar + "'"
        if ($content -match [regex]::Escape($pattern3)) {
            $content = $content -replace [regex]::Escape($pattern3), $replacement3
            $fileModified = $true
        }
    }

    if ($fileModified) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8 -NoNewline
        $modifiedFiles++
        Write-Host "[$processedFiles/$totalFiles] Modified: $($file.FullName)" -ForegroundColor Green
    } else {
        if ($processedFiles % 100 -eq 0) {
            Write-Host "[$processedFiles/$totalFiles] Processed..." -ForegroundColor Gray
        }
    }
}

Write-Host "`n===================================" -ForegroundColor Cyan
Write-Host "Environment variable rename complete!" -ForegroundColor Cyan
Write-Host "Total files processed: $totalFiles" -ForegroundColor White
Write-Host "Files modified: $modifiedFiles" -ForegroundColor Green
Write-Host "===================================`n" -ForegroundColor Cyan
